#pragma once

#include "../tools/macro.hpp"

FARCONN_NAMESPACE_BEGIN(general)

enum class server_status_code {
	SYS__OKEY						  = 200,

	SYS__INVALID_COMMAND			  = 400,
	SYS__INVALID_TOKEN				  = 401,
	SYS__NONEXISTEN_USER              = 402,

	SIGNUP__EXISTING_LOGIN_ERROR	  = 403,
	SIGNUP__INVALID_LOGIN_ERROR		  = 404,
	SIGNUP__INVALID_PASSWORD_ERROR    = 405,
     
	LOGIN__INVALID_DATA_ERROR	      = 406,
	LOGIN__ALREADY_LOGGED_IN          = 407,

	SYS__INTERNAL_SERVER_ERROR		  = 500,
};

FARCONN_NAMESPACE_END