#pragma once

#include "handler.hpp"
#include "signup_handler.hpp"
#include "login_handler.hpp"
#include "logout_handler.hpp"
#include "profile_get_handler.hpp"
#include "profile_set_handler.hpp"
#include "invite_handler.hpp"
#include "invites_list_handler.hpp"
#include "contacts_list_handler.hpp"
#include "contact_delete_handler.hpp"
#include "search_handler.hpp"
#include "chat_create_handler.hpp"
#include "chat_add_handler.hpp"
#include "chat_leave_handler.hpp"